version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: vacation_db
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: pg_admin123
      POSTGRES_DB: vacation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 