version: '3.8'

services:
  postgres_staging:
    image: postgres:16
    container_name: vacation_db_staging
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vacation_db_staging
    ports:
      - "5432:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
      - ./SQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d vacation_db_staging"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:16
    container_name: vacation_db_test
    env_file: .env.test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vacation_db_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./SQL/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d vacation_db_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_staging_data:
  postgres_test_data: 